import type {
  Estabelecimento,
  Cliente,
  ProdutoCardapio,
  ItemListaCompra,
  ListaCompras,
  RegrasAgendamento,
} from "./caixadoce-data";

export const ESTABELECIMENTO_PADRAO: Estabelecimento = {
  id: "est-1",
  codigo: "CD-1001",
  nome: "CaixaDoce Matriz",
  endereco: "",
  cidade: "",
  estado: "",
  tipoDocumento: "CNPJ",
  numeroDocumento: "",
  chavePix: "",
  tipoChavePix: "email",
  responsavel: "",
  telefone: "",
  whatsapp: "",
  email: "",
  stripeAccountId: null,
  repassarTaxaStripe: true,
};

export const CLIENTES_PADRAO: Cliente[] = [
  {
    id: "cli-1",
    estabelecimentoCodigo: "CD-1001",
    nome: "Mariana Silva",
    whatsapp: "(11) 98765-4321",
    endereco: "Rua das Flores, 120 - Apto 42 - Jardim Paulista, São Paulo/SP",
    observacoes: "Cliente frequente de bolos decorados e brigadeiros.",
    createdAt: "2026-01-01T10:00:00.000Z",
  },
  {
    id: "cli-2",
    estabelecimentoCodigo: "CD-1001",
    nome: "Camila Guimarães",
    whatsapp: "(11) 97123-4567",
    endereco: "Av. Brigadeiro Luís Antônio, 3400 - Cerqueira César, São Paulo/SP",
    observacoes: "Prefere doces menos açucarados (Ninho e 50% Cacau).",
    createdAt: "2026-01-02T10:00:00.000Z",
  },
  {
    id: "cli-3",
    estabelecimentoCodigo: "CD-1001",
    nome: "Lucas Martins",
    whatsapp: "(11) 99888-7766",
    endereco: "Rua Augusta, 850 - Consolação, São Paulo/SP",
    observacoes: "Pede bentô cakes personalizados para aniversários.",
    createdAt: "2026-01-03T10:00:00.000Z",
  },
];

export const CATALOGO_PRODUTOS_PADRAO: ProdutoCardapio[] = [
  {
    id: "prod_1",
    estabelecimentoCodigo: "CD-1001",
    nome: "Bolo de Aniversário 2kg",
    descricao: "Massa pão de ló com recheio de brigadeiro gourmet e cobertura de chantininho.",
    preco: 140.0,
    categoria: "Bolos Decorados",
    fotoUrl: "https://images.unsplash.com/photo-1586788680434-30d324b2d46f?auto=format&fit=crop&w=600&q=80",
    destaque: true,
    tempoPreparoHoras: 24,
    ativo: true,
  },
  {
    id: "prod-3",
    estabelecimentoCodigo: "CD-1001",
    nome: "Caixa Brigadeiros Gourmet (12 un)",
    descricao: "Seleção com Brigadeiro Belga ao Leite, Ninho com Nutella, Churros com Doce de Leite e Pistache.",
    preco: 48.0,
    categoria: "Doces & Brigadeiros",
    fotoUrl: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?auto=format&fit=crop&w=600&q=80",
    destaque: true,
    tempoPreparoHoras: 12,
    ativo: true,
  },
  {
    id: "prod-4",
    estabelecimentoCodigo: "CD-1001",
    nome: "Bentô Cake Personalizado",
    descricao: "Mini bolo de 10cm com frase ou meme personalizado no topo. Ideal para presentes e comemorações intimistas.",
    preco: 45.0,
    categoria: "Bentô Cakes",
    fotoUrl: "https://images.unsplash.com/photo-1535141192574-5d4897c13136?auto=format&fit=crop&w=600&q=80",
    tempoPreparoHoras: 24,
    ativo: true,
  },
  {
    id: "prod-5",
    estabelecimentoCodigo: "CD-1001",
    nome: "Copo da Felicidade Ninho com Nutella",
    descricao: "Camadas de creme de Ninho, Nutella pura, brownie picado e morangos frescos.",
    preco: 22.0,
    categoria: "Copos & Sobremesas",
    fotoUrl: "https://images.unsplash.com/photo-1579372786545-d24232daf58c?auto=format&fit=crop&w=600&q=80",
    tempoPreparoHoras: 2,
    ativo: true,
  },
];

export const ITENS_COMPRA_PADRAO: ItemListaCompra[] = [
  {
    id: "ic-1",
    estabelecimentoCodigo: "CD-1001",
    nome: "Leite Condensado Moça 395g",
    quantidade: 6,
    unidade: "un",
    comprado: false,
    categoria: "Insumos",
    createdAt: "2026-01-01T10:00:00.000Z",
  },
  {
    id: "ic-2",
    estabelecimentoCodigo: "CD-1001",
    nome: "Cobertura Harald Melken Ao Leite 1kg",
    quantidade: 2,
    unidade: "kg",
    comprado: false,
    categoria: "Insumos",
    createdAt: "2026-01-01T10:00:00.000Z",
  },
  {
    id: "ic-3",
    estabelecimentoCodigo: "CD-1001",
    nome: "Embalagem para Bolo de Pote 250ml (caixa c/ 50)",
    quantidade: 1,
    unidade: "cx",
    comprado: true,
    categoria: "Embalagens",
    createdAt: "2026-01-01T10:00:00.000Z",
  },
];

export const LISTAS_COMPRAS_PADRAO: ListaCompras[] = [
  {
    id: "lc-1",
    nome: "Compras de Sexta",
    estabelecimentoCodigo: "CD-1001",
    estabelecimentosVinculados: ["Atacadão dos Confeiteiros S/A"],
    status: "ativa",
    itens: ITENS_COMPRA_PADRAO,
    createdAt: "2026-01-01T10:00:00.000Z",
  },
  {
    id: "lc-2",
    nome: "Festa da Maria",
    estabelecimentoCodigo: "CD-1001",
    estabelecimentosVinculados: ["ArtFesta Confeitaria & Embalagens"],
    status: "ativa",
    itens: [
      {
        id: "ic-201",
        estabelecimentoCodigo: "CD-1001",
        nome: "Chantilly Norcau 1L",
        quantidade: 4,
        unidade: "cx",
        comprado: false,
        clienteTags: ["Maria Silva"],
        createdAt: "2026-01-01T10:00:00.000Z",
      },
      {
        id: "ic-202",
        estabelecimentoCodigo: "CD-1001",
        nome: "Granulado Crocante Melken 500g",
        quantidade: 2,
        unidade: "pct",
        comprado: true,
        clienteTags: ["Maria Silva"],
        createdAt: "2026-01-01T10:00:00.000Z",
      },
    ],
    createdAt: "2026-01-01T10:00:00.000Z",
  },
  {
    id: "lc-3",
    nome: "Doces do Fim de Semana",
    estabelecimentoCodigo: "CD-1001",
    estabelecimentosVinculados: ["Supermercado Doce Preço Ltda"],
    status: "concluida",
    concluidaEm: "2026-01-01T10:00:00.000Z",
    itens: [
      {
        id: "ic-301",
        estabelecimentoCodigo: "CD-1001",
        nome: "Açúcar de Confeiteiro Impalpável 1kg",
        quantidade: 3,
        unidade: "kg",
        comprado: true,
        createdAt: "2026-01-01T10:00:00.000Z",
      },
    ],
    createdAt: "2026-01-01T10:00:00.000Z",
  },
];

export const CATEGORIAS_PADRAO = {
  receitas: [
    "Encomenda de Bolo / Doce",
    "Venda de Pronta Entrega",
    "Sinal / Entrada de Pedido",
    "Aporte de Capital / Investimento",
    "Outras Receitas",
  ],
  despesas: [
    "Insumos & Matérias-Primas",
    "Embalagens & Caixas",
    "Utensílios de Cozinha",
    "Energia Elétrica",
    "Água",
    "Gás de Cozinha",
    "Internet & Telefone",
    "Aluguel",
    "Impostos & Taxas",
    "Consumo Pessoal / Retirada",
    "Outras Despesas",
  ],
};

export const REGRAS_AGENDAMENTO_PADRAO: RegrasAgendamento = {
  estabelecimentoCodigo: "CD-1001",
  antecedenciaMinimaHoras: 24,
  permitirProntaEntregaDias: [3, 4, 5, 6], // Qua, Qui, Sex, Sáb
  horarioAbertura: "09:00",
  horarioFechamento: "19:00",
  intervaloEncaixesMinutos: 30,
};
