/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PedidoConfirmadoRouteImport } from './routes/pedido-confirmado'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AgendarStoreSlugRouteImport } from './routes/agendar.$storeSlug'
import { Route as CardapioIndexRouteImport } from './routes/cardapio.index'
import { Route as CardapioStoreCodeRouteImport } from './routes/cardapio.$storeCode'
import { Route as PagarCobrancaIdRouteImport } from './routes/pagar.$cobrancaId'
import { Route as PainelConfiguracoesRouteImport } from './routes/painel.configuracoes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoConfirmadoRoute = PedidoConfirmadoRouteImport.update({
  id: '/pedido-confirmado',
  path: '/pedido-confirmado',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarStoreSlugRoute = AgendarStoreSlugRouteImport.update({
  id: '/agendar/$storeSlug',
  path: '/agendar/$storeSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CardapioIndexRoute = CardapioIndexRouteImport.update({
  id: '/cardapio/',
  path: '/cardapio/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardapioStoreCodeRoute = CardapioStoreCodeRouteImport.update({
  id: '/cardapio/$storeCode',
  path: '/cardapio/$storeCode',
  getParentRoute: () => rootRouteImport,
} as any)
const PagarCobrancaIdRoute = PagarCobrancaIdRouteImport.update({
  id: '/pagar/$cobrancaId',
  path: '/pagar/$cobrancaId',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelConfiguracoesRoute = PainelConfiguracoesRouteImport.update({
  id: '/painel/configuracoes',
  path: '/painel/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/agendar/$storeSlug': typeof AgendarStoreSlugRoute
  '/cardapio/$storeCode': typeof CardapioStoreCodeRoute
  '/pagar/$cobrancaId': typeof PagarCobrancaIdRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/cardapio/': typeof CardapioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/agendar/$storeSlug': typeof AgendarStoreSlugRoute
  '/cardapio/$storeCode': typeof CardapioStoreCodeRoute
  '/pagar/$cobrancaId': typeof PagarCobrancaIdRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/cardapio': typeof CardapioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/pedido-confirmado': typeof PedidoConfirmadoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/termos': typeof TermosRoute
  '/agendar/$storeSlug': typeof AgendarStoreSlugRoute
  '/cardapio/$storeCode': typeof CardapioStoreCodeRoute
  '/pagar/$cobrancaId': typeof PagarCobrancaIdRoute
  '/painel/configuracoes': typeof PainelConfiguracoesRoute
  '/cardapio/': typeof CardapioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/landing'
    | '/login'
    | '/pedido-confirmado'
    | '/privacidade'
    | '/termos'
    | '/agendar/$storeSlug'
    | '/cardapio/$storeCode'
    | '/pagar/$cobrancaId'
    | '/painel/configuracoes'
    | '/cardapio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/landing'
    | '/login'
    | '/pedido-confirmado'
    | '/privacidade'
    | '/termos'
    | '/agendar/$storeSlug'
    | '/cardapio/$storeCode'
    | '/pagar/$cobrancaId'
    | '/painel/configuracoes'
    | '/cardapio'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/landing'
    | '/login'
    | '/pedido-confirmado'
    | '/privacidade'
    | '/termos'
    | '/agendar/$storeSlug'
    | '/cardapio/$storeCode'
    | '/pagar/$cobrancaId'
    | '/painel/configuracoes'
    | '/cardapio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  PedidoConfirmadoRoute: typeof PedidoConfirmadoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosRoute: typeof TermosRoute
  AgendarStoreSlugRoute: typeof AgendarStoreSlugRoute
  CardapioStoreCodeRoute: typeof CardapioStoreCodeRoute
  PagarCobrancaIdRoute: typeof PagarCobrancaIdRoute
  PainelConfiguracoesRoute: typeof PainelConfiguracoesRoute
  CardapioIndexRoute: typeof CardapioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido-confirmado': {
      id: '/pedido-confirmado'
      path: '/pedido-confirmado'
      fullPath: '/pedido-confirmado'
      preLoaderRoute: typeof PedidoConfirmadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar/$storeSlug': {
      id: '/agendar/$storeSlug'
      path: '/agendar/$storeSlug'
      fullPath: '/agendar/$storeSlug'
      preLoaderRoute: typeof AgendarStoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardapio/': {
      id: '/cardapio/'
      path: '/cardapio'
      fullPath: '/cardapio/'
      preLoaderRoute: typeof CardapioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cardapio/$storeCode': {
      id: '/cardapio/$storeCode'
      path: '/cardapio/$storeCode'
      fullPath: '/cardapio/$storeCode'
      preLoaderRoute: typeof CardapioStoreCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagar/$cobrancaId': {
      id: '/pagar/$cobrancaId'
      path: '/pagar/$cobrancaId'
      fullPath: '/pagar/$cobrancaId'
      preLoaderRoute: typeof PagarCobrancaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/configuracoes': {
      id: '/painel/configuracoes'
      path: '/painel/configuracoes'
      fullPath: '/painel/configuracoes'
      preLoaderRoute: typeof PainelConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  PedidoConfirmadoRoute: PedidoConfirmadoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosRoute: TermosRoute,
  AgendarStoreSlugRoute: AgendarStoreSlugRoute,
  CardapioStoreCodeRoute: CardapioStoreCodeRoute,
  PagarCobrancaIdRoute: PagarCobrancaIdRoute,
  PainelConfiguracoesRoute: PainelConfiguracoesRoute,
  CardapioIndexRoute: CardapioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
